// 由 scripts/embed-migrations.mjs 根据 migrations/ 生成，不要手动修改。
import type { Migration } from './migrate.js'

export const migrations: readonly Migration[] = [
  {
    tag: '0000_init',
    sql: 'CREATE TABLE `fetch_logs` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`source_id` text NOT NULL,\n\t`at` integer NOT NULL,\n\t`status` text NOT NULL,\n\t`bytes` integer,\n\t`duration_ms` integer,\n\t`error` text,\n\tFOREIGN KEY (`source_id`) REFERENCES `sources`(`id`) ON UPDATE no action ON DELETE cascade\n);\n--> statement-breakpoint\nCREATE INDEX `fetch_logs_source_id_idx` ON `fetch_logs` (`source_id`,`id`);--> statement-breakpoint\nCREATE TABLE `outputs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`profile_id` text NOT NULL,\n\t`target` text NOT NULL,\n\t`token` text NOT NULL,\n\t`options_json` text NOT NULL,\n\t`last_access_at` integer,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`profile_id`) REFERENCES `profiles`(`id`) ON UPDATE no action ON DELETE cascade\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `outputs_token_unique` ON `outputs` (`token`);--> statement-breakpoint\nCREATE INDEX `outputs_profile_id_idx` ON `outputs` (`profile_id`);--> statement-breakpoint\nCREATE TABLE `profiles` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`ir_json` text NOT NULL,\n\t`pipeline_json` text NOT NULL,\n\t`source_ids_json` text NOT NULL,\n\t`updated_at` integer NOT NULL,\n\t`created_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `settings` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` text NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `sources` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`url_enc` text,\n\t`content` text,\n\t`user_agent` text,\n\t`ttl_sec` integer NOT NULL,\n\t`last_fetched_at` integer,\n\t`last_status` text,\n\t`last_error` text,\n\t`userinfo_json` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n',
  },
]
